### ISSUE TITLE
Action error

### ISSUE THREAD

**Issue by aaduo01** [zhtok/MSO_E5_Dev_AutoRenew_Modified#3]
Hi Mate! Every time run workflows action same problem. 
Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  File "temp.py", line 11
    ***
                                          ^
SyntaxError: EOL while scanning string literal
Error: Process completed with exit code 1.

**Comment by zhtok** [comment]
The author DO NOT provide help or further assistance for personal reasons.
