### ISSUE TITLE
Actions are skipped

### ISSUE THREAD

**Issue by l-Nuril-l** [zhtok/MSO_E5_Dev_AutoRenew_Modified#4]
just notifying

**Comment by ang3lo-azevedo** [comment]
Yeah, does anyone know what is happening?

**Comment by zhtok** [comment]
Problem fixed with [#3f59c67](https://github.com/zhtok/MSO_E5_Dev_AutoRenew_Modified/commit/3f59c67813d1df9d09b98cb11ac619b447e8e953)

**Comment by seth-aung** [comment]
Can I get previous read-me instructions please. I don't remember some steps.
